### ISSUE TITLE
Need your guidance

### ISSUE THREAD

**Issue by ghost** [INGEOTEC/microTC#30]
Greetings!!!
                  I am a beginner, I am pleased to ask whether can we change scale of funniness score in this code. I have tried but I couldn't do that. So, can you please help me to change the scale of funniness score. Thanks in advance.

**Comment by mgraffg** [comment]
Dear Kayal,

microTC does not have any funniness score; perhaps you might get confused because we have used microTC on the HAHA Competition (https://www.fing.edu.uy/inco/grupos/pln/haha/). 

Our developments (https://github.com/ingeotec/), microTC, b4msa, and EvoMSA, tackle the problem of text classification; microTC also addresses it as a regression problem. 
This problem starts with a training set (see the doc of EvoMSA https://evomsa.readthedocs.io/en/latest/), it is on the training set where the score or the class is provided. 

I hope this information helps you if you have any trouble, please do not hesitate to contact us again. 

Best regards, 

Mario
